### ISSUE TITLE
Liebefeld: 12th frame

### ISSUE THREAD

**Issue by mato74** [beepnl/beep-vue-app-legacy-api#12]
@JuliaBD Please add 12th frame per brood layer in Liebefeld method. As max. 2 brood layers can be selected, it means additionof frame 23 and 24 with each a side A an B. These have been added to the data categories already. In practice: user needs to be able to select 12 frames per layer and 12th frame need to be included in the bee count.

**Comment by JuliaBD** [comment]
Done
