### ISSUE TITLE
New API token not changed in VUE data store

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#14]
If I change the user locale (or any other user property), the resulting user object contains an updated API token:
```
{"id":999999,"name":"beep1@iconize.nl","email":"beep1@iconize.nl","avatar":"default.jpg","api_token":"*****************************************","created_at":"2020-05-11 08:55:57","updated_at":"2020-12-12 18:01:52","last_login":"2020-12-12 18:01:31","policy_accepted":null,"email_verified_at":"2020-05-11 08:56:04","locale":"nl","app_debug":false}
```
But since the updated token is not interpreted by the VUE data store, the consecutive API calls (having the old API token in the Header Authentication) all fail.

Please update the user. api_token with the result from every POST or PATCH call to the /user end point.

**Comment by JuliaBD** [comment]
Closed.
