### ISSUE TITLE
Primary buttons not in primary color

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#23]
The following buttons should be in black in stead of yellow:

Edit Devices: https://appv3.beep.nl/measurements
Add alert rule: https://appv3.beep.nl/alertrules
Edit checklist + Date of inspection: https://appv3.beep.nl/hives/166/inspections/196
Add own device + (open settings) Add sensor definition : https://appv3.beep.nl/devices

**Comment by JuliaBD** [comment]
Done! (not live yet).
in darker yellow color instead of black  :)
