### ISSUE TITLE
Alerts should be reloaded by clicking on Alerts menu tab

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#25]
Alerts should be reloaded by clicking on Alerts menu tab. Now this is only done at clicking on Home (apiary) menu tab.

**Comment by JuliaBD** [comment]
Done

**Comment by pvgennip** [comment]
Does not yet seem to work, or I get no visual loading sign.

Also important to update the '... minutes ago' time visualization upon reload

**Comment by JuliaBD** [comment]
Fixed (not on test server yet)
