### ISSUE TITLE
Create clear call to action button for first AlertRule

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#26]
Now the step to create the first AlertRule is a bit hidden below the page fold as a link.

Please make a clear call to action leading to the AlertRule create/copy menu

 ![image](https://user-images.githubusercontent.com/7629987/117352285-1c2aaa00-aeaf-11eb-961e-e84547f999c9.jpeg)

**Comment by JuliaBD** [comment]
Done
