### ISSUE TITLE
Back button after save action should not go back to the edit item screen

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#27]
The function of the back button is not meaningful if it goes back to a just saved item after saving (e.g. after saving an alert rule it goes to AlertRules, but pressing back brings you back to the edit screen. I would expect it to go to the Alerts view).

Please remove the step of going back to an edited item from the history, or let the back button go back to the logical screen in hierarchy.

**Comment by JuliaBD** [comment]
Done
