### ISSUE TITLE
Refreshing apiary details view results in 404 (not found)

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#3]
Refreshing apiary details view results in 404 (not found)
https://appv3.beep.nl/apiaries/28

Refreshing https://appv3.beep.nl however, does work.

**Comment by JuliaBD** [comment]
@pvgennip Vue router uses history mode, which may require server configuration on production: https://router.vuejs.org/guide/essentials/history-mode.html#example-server-configurations

**Comment by pvgennip** [comment]
Fixed by including in Apache config
```
<IfModule mod_rewrite.c>
      RewriteEngine On
      RewriteBase /
      RewriteRule ^index\.html$ - [L]
      RewriteCond %{REQUEST_FILENAME} !-f
      RewriteCond %{REQUEST_FILENAME} !-d
      RewriteRule . /index.html [L]
    </IfModule>
```
