### ISSUE TITLE
Alert rule: remove Dutch lidwoorden

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#40]
The function in Dutch says: "Ik wil een notificatie ontvangen als de telling van de/het waarde van de/het Batterij gelijk is aan 0V. Deze berekening wordt elke 0.5 uur uitgevoerd, en ik ontvang hier direct een notificatie van."

It would be better readable if it was: "Ik wil een notificatie ontvangen als **het aantal keer voorkomen van Batterij voltage waarde** gelijk is aan 0. Deze berekening wordt elke 0.5 uur uitgevoerd, en ik ontvang hier direct een notificatie van."

NB: 

- telling => aantal keer voorkomen van
- Batterij => Batterij voltage

**Comment by JuliaBD** [comment]
Tbt on test
