### ISSUE TITLE
Alert rule: make calculation minutes selection a dropdown

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#41]
We would like encourage users not to parse rules too often. Please set the default at 3 hours. 

Replace the minute stepper with dropdown with these options:

- 15 min
- 30 min
- 1 hour
- 3 hours
- 6 hours
- 12 hours
- 24 hours
- 48 hours

**Comment by JuliaBD** [comment]
Tbt on test
