### ISSUE TITLE
New alert rule gives blank screen

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#46]
![image](https://user-images.githubusercontent.com/7629987/135132190-b629f093-344d-45c3-b3c8-9dce7aaca0a6.png)

Maybe is the caching of the taxonomy/lists that does not contain 'show_in_alerts' yet

**Comment by JuliaBD** [comment]
solved by adding show_in_alerts? for me it's solved at least
