### ISSUE TITLE
Inspection edit ‘back’ loop

### ISSUE THREAD

**Issue by pvgennip** [beepnl/beep-vue-app-legacy-api#47]
If I edit an inspection and save it, and I want to go back to the inspections overview, I oress the back button. This leads me back to the inspection edit screen, but since I just saved the inspection, I would think I would go back to the main inspection overview screen.

Please make the back button in the detail screen always go back to the main screen to avoid the feeling of an endless back loop.

**Comment by JuliaBD** [comment]
From where did you edit the inspection and from where did you want to go back to the inspections overview? @pvgennip? Apparently after saving the inspection you were directed to an unexpected / unwanted view?

**Comment by JuliaBD** [comment]
I expect this happened when editing or creating an inspection from the inspections overview (detailed version per hive). After saving the inspection, you are directed back to the inspections overview. From there you want to go back NOT to the inspection screen again (which is what happened), but to where you came from initially (desired outcome).

If that's correct, it's fixed now @ test :)
